export const DEFAULT_OVO_NEUTRAL = {
  master_enabled: true,
  seo_enabled: true,
  geo_enabled: true,
  aeo_enabled: true,
  llmo_enabled: true,
  eeo_enabled: true,
  kgo_enabled: true,
  reo_enabled: true,
  sgeo_enabled: true,

  brand: {
    name: "",
    alt_names: [],
    legal_name: "",
    slogan: "",
    description: "",
    logo_url: "",
    founding_year: "",
    founding_place: "",
    parent_org: null,
    contact_points: [],
    postal_address: null,
    founders: [],
    press_mentions: [],
  },
  default_meta: {
    title_default: "",
    title_template: "%s",
    description_fallback: "",
    keywords: [],
    og_image_url: null,
    twitter_handle: null,
    locale: "en",
  },
  robots: {
    disallow_paths: [],
    sitemap_url: null,
  },
  sitemap_shards: {
    static: true,
    products: false,
    taxonomy: false,
    knowledge: false,
  },
  entity: {
    same_as: [],
    knows_about: [],
    services: [],
  },
  faq: [],
  default_product_faq: [],
  default_category_faq: [],
  citations: {
    author: null,
    reviewer: null,
    last_updated: null,
  },
  llms_txt: {
    short_md: "",
    full_md: "",
  },
  bot_policy: {
    retrieval_bots: "allow",
    training_bots: "deny",
    scraper_bots: "deny",
    overrides: {},
  },
  retrieval: {
    prefer_h2_breaks: true,
    chunk_size_tokens: 800,
    emit_jsonl_export: false,
  },
  generative: {
    question_intent_keywords: [],
    summary_paragraph: "",
    source_attribution_text: "",
  },
  keyword_tracking: {
    default_country: "US",
    default_language: "en",
    default_difficulty_provider: "none",
    gsc_property_url: null,
    snapshot_window_days: 28,
    rollup_matching: "exact",
    auto_status_threshold: {
      won_position_max: 10,
      lost_regression_ranks: 3,
    },
    bulk_import_cap: 5000,
  },
}
