// @ts-nocheck
export const DEFAULT_SMS_TEMPLATES = [
  {
    slug: "auth.phone_otp_login",
    label: "Phone login OTP",
    description: "One-time password for phone sign-in.",
    body: "{{brand}} OTP is {{otp}}. It expires in {{expiry_minutes}} minutes.",
    variables: ["brand", "otp", "expiry_minutes"],
    is_otp: true,
  },
  {
    slug: "order.placed",
    label: "Order placed",
    body: "Hi {{customer.first_name}}, your {{brand}} order {{order.display_id}} has been placed. Total: {{amount}}.",
    variables: ["customer.first_name", "brand", "order.display_id", "amount"],
    is_otp: false,
  },
  {
    slug: "order.completed",
    label: "Order completed",
    body: "Your {{brand}} order {{order.display_id}} is complete. Thank you for shopping with us!",
    variables: ["brand", "order.display_id"],
    is_otp: false,
  },
  {
    slug: "order.cancelled",
    label: "Order cancelled",
    body: "Your {{brand}} order {{order.display_id}} has been cancelled. Contact {{support_email}} for assistance.",
    variables: ["brand", "order.display_id", "support_email"],
    is_otp: false,
  },
  {
    slug: "customer.created",
    label: "Customer created",
    body: "Welcome to {{brand}}, {{customer.first_name}}! Your account has been created.",
    variables: ["brand", "customer.first_name"],
    is_otp: false,
  },
  {
    slug: "customer.approved",
    label: "Customer approved",
    body: "Hi {{customer.first_name}}, your {{brand}} account has been approved. You can now place orders.",
    variables: ["brand", "customer.first_name"],
    is_otp: false,
  },
  {
    slug: "customer.rejected",
    label: "Customer rejected",
    body: "Hi {{customer.first_name}}, your {{brand}} account application could not be approved at this time.",
    variables: ["brand", "customer.first_name"],
    is_otp: false,
  },
  {
    slug: "kyc.approved",
    label: "KYC approved",
    body: "Your KYC has been approved on {{brand}}. You now have full access.",
    variables: ["brand"],
    is_otp: false,
  },
  {
    slug: "kyc.rejected",
    label: "KYC rejected",
    body: "Your KYC on {{brand}} was rejected. Please contact {{support_email}}.",
    variables: ["brand", "support_email"],
    is_otp: false,
  },
  {
    slug: "password.reset",
    label: "Password reset",
    body: "Your {{brand}} password reset code is {{otp}}. It expires in {{expiry_minutes}} minutes.",
    variables: ["brand", "otp", "expiry_minutes"],
    is_otp: false,
  },
]

export const DEFAULT_WHATSAPP_TEMPLATES = [
  {
    slug: "auth.phone_otp_login",
    name: "auth_phone_otp_login",
    label: "Phone login OTP",
    category: "AUTHENTICATION",
    language: "en_US",
    template_type: "STANDARD",
    components: [
      { type: "BODY", text: "{{1}} is your {{brand}} verification code." },
      { type: "FOOTER", text: "This code expires in {{2}} minutes." },
    ],
    variables: ["otp", "expiry_minutes", "brand"],
    is_otp: true,
  },
  {
    slug: "order.placed",
    name: "order_placed",
    label: "Order placed",
    category: "UTILITY",
    language: "en_US",
    template_type: "STANDARD",
    components: [
      { type: "BODY", text: "Hi {{customer.first_name}}, your {{brand}} order {{order.display_id}} has been placed." },
    ],
    variables: ["customer.first_name", "brand", "order.display_id"],
    is_otp: false,
  },
  {
    slug: "order.completed",
    name: "order_completed",
    label: "Order completed",
    category: "UTILITY",
    language: "en_US",
    template_type: "STANDARD",
    components: [
      { type: "BODY", text: "Your {{brand}} order {{order.display_id}} is complete." },
    ],
    variables: ["brand", "order.display_id"],
    is_otp: false,
  },
  {
    slug: "order.cancelled",
    name: "order_cancelled",
    label: "Order cancelled",
    category: "UTILITY",
    language: "en_US",
    template_type: "STANDARD",
    components: [
      { type: "BODY", text: "Your {{brand}} order {{order.display_id}} has been cancelled." },
    ],
    variables: ["brand", "order.display_id"],
    is_otp: false,
  },
  {
    slug: "customer.created",
    name: "customer_created",
    label: "Customer created",
    category: "UTILITY",
    language: "en_US",
    template_type: "STANDARD",
    components: [
      { type: "BODY", text: "Welcome to {{brand}}, {{customer.first_name}}!" },
    ],
    variables: ["brand", "customer.first_name"],
    is_otp: false,
  },
  {
    slug: "kyc.approved",
    name: "kyc_approved",
    label: "KYC approved",
    category: "UTILITY",
    language: "en_US",
    template_type: "STANDARD",
    components: [
      { type: "BODY", text: "Your KYC has been approved on {{brand}}." },
    ],
    variables: ["brand"],
    is_otp: false,
  },
  {
    slug: "kyc.rejected",
    name: "kyc_rejected",
    label: "KYC rejected",
    category: "UTILITY",
    language: "en_US",
    template_type: "STANDARD",
    components: [
      { type: "BODY", text: "Your KYC on {{brand}} was rejected. Contact {{support_email}}." },
    ],
    variables: ["brand", "support_email"],
    is_otp: false,
  },
]

export const DEFAULT_EMAIL_TEMPLATES = [
  {
    slug: "order.placed",
    label: "Order placed",
    subject: "{{brand}} order {{order.display_id}} confirmed",
    html: "<h1>Order confirmed</h1><p>Hi {{customer.first_name}}, your order <strong>{{order.display_id}}</strong> has been placed.</p><p>Total: <strong>{{amount}}</strong></p><p>Thank you for shopping with {{brand}}!</p>",
    variables: ["brand", "order.display_id", "customer.first_name", "amount"],
  },
  {
    slug: "order.completed",
    label: "Order completed",
    subject: "Your {{brand}} order {{order.display_id}} is complete",
    html: "<h1>Order complete</h1><p>Your order <strong>{{order.display_id}}</strong> is complete.</p><p>Thank you for shopping with {{brand}}!</p>",
    variables: ["brand", "order.display_id"],
  },
  {
    slug: "order.cancelled",
    label: "Order cancelled",
    subject: "{{brand}} order {{order.display_id}} cancelled",
    html: "<h1>Order cancelled</h1><p>Your order <strong>{{order.display_id}}</strong> has been cancelled.</p><p>If you have questions, contact {{support_email}}.</p>",
    variables: ["brand", "order.display_id", "support_email"],
  },
  {
    slug: "customer.created",
    label: "Customer created",
    subject: "Welcome to {{brand}}!",
    html: "<h1>Welcome, {{customer.first_name}}!</h1><p>Your account has been created on {{brand}}.</p><p>Visit {{storefront_url}} to start shopping.</p>",
    variables: ["brand", "customer.first_name", "storefront_url"],
  },
  {
    slug: "customer.approved",
    label: "Customer approved",
    subject: "Your {{brand}} account has been approved",
    html: "<h1>Account approved</h1><p>Hi {{customer.first_name}}, your {{brand}} account has been approved.</p><p>You can now place orders at {{storefront_url}}.</p>",
    variables: ["brand", "customer.first_name", "storefront_url"],
  },
  {
    slug: "customer.rejected",
    label: "Customer rejected",
    subject: "{{brand}} account update",
    html: "<h1>Account update</h1><p>Hi {{customer.first_name}}, your {{brand}} account application could not be approved at this time.</p><p>Contact {{support_email}} for more information.</p>",
    variables: ["brand", "customer.first_name", "support_email"],
  },
  {
    slug: "kyc.approved",
    label: "KYC approved",
    subject: "Your KYC has been approved on {{brand}}",
    html: "<h1>KYC approved</h1><p>Your KYC has been approved on {{brand}}. You now have full access to all features.</p>",
    variables: ["brand"],
  },
  {
    slug: "kyc.rejected",
    label: "KYC rejected",
    subject: "Your KYC on {{brand}} was rejected",
    html: "<h1>KYC rejected</h1><p>Your KYC on {{brand}} was rejected. Please contact {{support_email}} for assistance.</p>",
    variables: ["brand", "support_email"],
  },
  {
    slug: "password.reset",
    label: "Password reset",
    subject: "{{brand}} password reset code",
    html: "<h1>Password reset</h1><p>Your password reset code is: <strong>{{otp}}</strong></p><p>This code expires in {{expiry_minutes}} minutes.</p>",
    variables: ["brand", "otp", "expiry_minutes"],
  },
]

export const DEFAULT_EVENT_RULES = [
  { event_name: "order.placed", channel: "email", template_slug: "order.placed" },
  { event_name: "order.placed", channel: "sms", template_slug: "order.placed" },
  { event_name: "order.placed", channel: "whatsapp", template_slug: "order.placed" },
  { event_name: "order.completed", channel: "email", template_slug: "order.completed" },
  { event_name: "order.completed", channel: "sms", template_slug: "order.completed" },
  { event_name: "order.completed", channel: "whatsapp", template_slug: "order.completed" },
  { event_name: "order.cancelled", channel: "email", template_slug: "order.cancelled" },
  { event_name: "order.cancelled", channel: "sms", template_slug: "order.cancelled" },
  { event_name: "order.cancelled", channel: "whatsapp", template_slug: "order.cancelled" },
  { event_name: "customer.created", channel: "email", template_slug: "customer.created" },
  { event_name: "customer.created", channel: "sms", template_slug: "customer.created" },
  { event_name: "customer.created", channel: "whatsapp", template_slug: "customer.created" },
  { event_name: "customer.approved", channel: "email", template_slug: "customer.approved" },
  { event_name: "customer.rejected", channel: "email", template_slug: "customer.rejected" },
  { event_name: "kyc.approved", channel: "email", template_slug: "kyc.approved" },
  { event_name: "kyc.approved", channel: "whatsapp", template_slug: "kyc.approved" },
  { event_name: "kyc.rejected", channel: "email", template_slug: "kyc.rejected" },
  { event_name: "kyc.rejected", channel: "whatsapp", template_slug: "kyc.rejected" },
  { event_name: "customer.login", channel: "sms", template_slug: "auth.phone_otp_login" },
  { event_name: "password.reset", channel: "email", template_slug: "password.reset" },
  { event_name: "password.reset", channel: "sms", template_slug: "password.reset" },
]
